name: atomlib
description: "Atom store library"
version: 0.0.7
homepage: https://github.com/tranvansang/atomlib
environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter: